### PR TITLE
Adding translation into Spanish for 02-execution-context.md

### PR DESCRIPTION
**Pull request by enriquezrene**
Adding translation into Spanish for 02-execution-context.md

### CODE REVIEW

**Comment by enriquezrene** [comment]
It would be great if you guys label this repo as hacktoberfest-accepted :slightly_smiling_face:

**Comment by novemberborn** [comment]
Thanks for contributing @enriquezrene!

Would you happen to know anybody who can review your translation? It's always good to get another pair of eyes on things.

**Comment by enriquezrene** [comment]
Sure, let's add @chelohidalgo

**Comment by chelohidalgo** [comment]
Hy guys, It's looks good to me. Thanks for your message.

**Comment by novemberborn** [comment]
Thanks for taking a look @chelohidalgo!

**Comment by enriquezrene** [comment]
Great @novemberborn 
Do you think we can add the label `hacktoberfest-accepted` to this PR so it can be part of the [HactoberFest](https://hacktoberfest.digitalocean.com/)?

**Pull request merged**
