### PR TITLE
Improve russian translations

### PR DESCRIPTION
**Pull request by forresst**
- Add head For the 2 new recipes (typescript and browser testing)
- Add link to russian translations

### CODE REVIEW

**Comment by forresst** [comment]
@sohje to review please. Thanks

**Comment by sohje** [comment]
@forresst All good. But - do we really need a link to current page if we already on russian translated page version?

**Comment by forresst** [comment]
@sohje You are right. This is not very logical. I would do later a PR that will remove the original language of the file (in this case Russian) by the English. I also do it for all files translated into all languages.

**Comment by sohje** [comment]
@forresst Yeap, thanks! I'll update russian translation to the latest commits soon(match, compare links, etc)

**Comment by forresst** [comment]
:+1:

**Pull request merged**
