### PR TITLE
[WIP] Translate documentation eslint-plugin-ava in french

### PR DESCRIPTION
**Pull request by forresst**
WIP translating documentation eslint-plugin-ava in french

As AVA, make the translation of eslint-plugin-ava documentation.
This WIP should allow validate the directory structure (The names and directory structure can be changed). Your opinion interests me. (cc @jfmengels @twada Your opinion interests me too)

Already done:
- [X] translate in french `readme.md`
- [X] translate in french `assertion-message.md`
- [X] translate in french `max-asserts.md`
- [X] translate in french `no-cb-test.md`
- [X] translate in french `no-identical-title.md`
- [X] translate in french `no-ignored-test-files.md`
- [X] translate in french `no-invalid-end.md`
- [X] translate in french `no-only-test.md`
- [X] translate in french `no-skip-assert.md`
- [X] translate in french `no-skip-test.md`
- [X] translate in french `no-statement-after-end.md`
- [X] translate in french `no-todo-test.md`
- [X] translate in french `no-unknown-modifiers.md`
- [X] translate in french `prefer-power-assert.md`
- [X] translate in french `test-ended.md`
- [X] translate in french `test-title.md`
- [X] translate in french `use-t-well.md`
- [X] translate in french `use-t.md`
- [X] translate in french `use-test.md`
- [X] translate in french `use-true-false.md`

And:
- [X] check corrects links in all files

### CODE REVIEW

**Comment by jfmengels** [comment]
LGTM :)
Thanks @forresst!

**Comment by dej611** [comment]
Ok, so the `ava-docs` project covers everything about AVA in general? I thought it was specifically related to the AVA repo.
I'll have a look at those files then for the Italian translation as well.

**Comment by forresst** [comment]
@dej611 It is a proposal (WIP), I expect a review. This does not mean yet that this will be accepted. In addition the directory structure can change depending on the view.

Wait maybe a little before starting

**Comment by novemberborn** [comment]
I'm :+1: on collecting official translations of official AVA projects here. Directory structure looks good too.

**Comment by forresst** [comment]
Completed.
@sindresorhus @novemberborn @vdemedes @jamestalmage 
You can merge if it's ok for you

**Comment by jamestalmage** [comment]
Awesome work @forresst! As always.

Directory structure looks great.

**Comment by jfmengels** [comment]
Great job @forresst!
Curious to know how many users go read the French docs (I'm a native French speaker too). Do you have any data or feedback from readers?

**Comment by forresst** [comment]
@jfmengels @jamestalmage Thanks !

> Do you have any data or feedback from readers?

Nope ! Except this [link](https://github.com/sindresorhus/ava-docs/graphs/traffic), but is not complete enough to know

**Comment by jfmengels** [comment]
Which I don't have access to (but thanks, didn't even know that existed!)

**Pull request merged**
