### PR TITLE
Translate React recipe to Spanish (es_ES)

### PR DESCRIPTION
**Pull request by kutyel**
Adds recipe to test **React components** in Spanish! :es:

### CODE REVIEW

**Comment by sindresorhus** [comment]
Awesome! :)

// @AlbertoFuente

**Comment by kutyel** [comment]
@sindresorhus Is that guy still alive? :worried: :laughing:

**Comment by forresst** [comment]
Is anyone else could proofread?

**Comment by sindresorhus** [comment]
@kutyel Can you add it here: https://github.com/avajs/ava-docs/tree/master/es_ES#recetas

**Comment by kutyel** [comment]
@sindresorhus Done, also sorted them alphabetically cause I saw it was the case in English. :wink:

**Comment by sindresorhus** [comment]
@kutyel They're not sorted alphabetically in the English version.

**Comment by sindresorhus** [comment]
Use the same order as the English version.

**Comment by kutyel** [comment]
@sindresorhus Done. I'm sorry I meant that I _thought_ that it was sorted alphabetically, didn't had time to double check it, now it should be fine.

**Comment by sindresorhus** [comment]
Thank you @kutyel :)

**Comment by kutyel** [comment]
You are welcome @sindresorhus :smile:

**Pull request merged**
