### PR TITLE
Spanish translation for the command line docs

### PR DESCRIPTION
**Pull request by enriquezrene**
Command line translation

### CODE REVIEW

**Comment by enriquezrene** [comment]
Hey @chelohidalgo, if you have some time please revew this one as well

**Comment by chelohidalgo** [comment]
It looks good to me @enriquezrene , go ahead!

**Comment by enriquezrene** [comment]
Great @novemberborn 
Whenever you can, merge it please 😉

**Comment by novemberborn** [comment]
Thank you both!

**Pull request merged**
