### PR TITLE
Adding translation into Spanish for 01-writting-tests

### PR DESCRIPTION
**Pull request by enriquezrene**

### CODE REVIEW

**Comment by novemberborn** [comment]
Thank you!

Do you know anybody who could double-check the translation? A second pair of eyes can be useful, what do you think?

**Comment by enriquezrene** [comment]
Definitively, let me see if I'm able to find someone

**Comment by enriquezrene** [comment]
@novemberborn, I will add @chelohidalgo as reviewer. He is a native Spanish speaker.

**Comment by enriquezrene** [comment]
Actually, I can't, could you please add him? 
This is his username @chelohidalgo

**Comment by novemberborn** [comment]
Hi @chelohidalgo 👋 Feel free to leave comments on the PR, there's no need to officially designate you as a reviewer. (In fact, I don't think I can until you comment here.)

**Comment by chelohidalgo** [comment]
Hi @novemberborn @enriquezrene thank you so much. It looks good to me, this is new but it is ok.

**Review by chelohidalgo — COMMENTED** [review]
It looks good to me.

**Comment by novemberborn** [comment]
Thank you @enriquezrene & @chelohidalgo!

**Pull request merged**
